import { toApiError, ApiError } from './errors.js';

// Every admin path starts here. Vite proxies /api to localhost:8080 in dev, so there is
// one origin, no CORS to configure, and no base URL to swap at build time.
const BASE = '/api/admin/v1';

// Both tokens live in this module, in memory only.
//
// Not localStorage and not sessionStorage: an XSS reads both, and the pre-commit hook
// blocks writing a token to either. The cost is that a page reload signs you out. That is
// deliberate for the prototype. The proper fix is for the backend to set the refresh token
// as an httpOnly cookie, which the browser cannot read at all.
//
// They sit here rather than in AuthContext because this file is what needs them: it attaches
// the access token to every request, and trades the refresh token for a new one when the
// access token expires.
let accessToken = null;
let refreshToken = null;

// Called when the server says the session is over, so the app can show the login page.
// Set once by AuthProvider. Kept as a callback rather than importing React state, so this
// file stays plain JavaScript with no React dependency.
let onAuthFailure = null;

export function setTokens({ accessToken: access = null, refreshToken: refresh = null } = {}) {
  accessToken = access;
  refreshToken = refresh;
}

export function clearTokens() {
  accessToken = null;
  refreshToken = null;
}

export function getAccessToken() {
  return accessToken;
}

export function getRefreshToken() {
  return refreshToken;
}

export function setAuthFailureHandler(fn) {
  onAuthFailure = fn;
}

// Spring writes its CSRF token to a readable `XSRF-TOKEN` cookie and expects it echoed back in
// an `X-XSRF-TOKEN` header. Reading a cookie is one line and not worth a dependency.
//
// Deliberately readable, unlike the refresh cookie: the point of a CSRF token is that a script
// on OUR origin can read it and a page on another origin cannot. It is not a secret, it is
// proof of same-origin.
function readCookie(name) {
  const match = document.cookie.match(new RegExp(`(?:^|; )${name}=([^;]*)`));
  return match ? decodeURIComponent(match[1]) : null;
}

/** Builds the headers for one request. Separate so `request` stays readable. */
function buildHeaders(hasBody, method, isForm) {
  const headers = { Accept: 'application/json' };
  if (accessToken) headers.Authorization = `Bearer ${accessToken}`;
  // No Content-Type at all for a FormData body, and deliberately not `multipart/form-data`
  // either. The boundary that separates the parts is generated by fetch when it serialises
  // the FormData, and it can only travel in the header fetch writes itself. Setting the
  // header here produces one with no boundary, which the server cannot split.
  if (hasBody && !isForm) headers['Content-Type'] = 'application/json';

  // Only on the methods that change something, which is all Spring checks. Sending it before
  // the backend enables CSRF is harmless: nothing reads it, and there is no cookie to read yet
  // so the header is simply absent. That is what lets this land ahead of the backend change
  // instead of in lockstep with it.
  if (method !== 'GET' && method !== 'HEAD') {
    const csrf = readCookie('XSRF-TOKEN');
    if (csrf) headers['X-XSRF-TOKEN'] = csrf;
  }
  return headers;
}

/**
 * Reads the body and parses it if it is JSON.
 *
 * Defensive on purpose. A proxy, a gateway or a crash can answer with HTML or with nothing,
 * and the console must report that rather than throwing a parse error at the operator.
 */
async function parseBody(response) {
  if (response.status === 204) return null;
  const text = await response.text();
  if (!text) return null;
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

/** Sends one request and reads the answer. No token handling, no retry: that is `request`. */
async function send(method, path, { body, signal }) {
  let response;
  // An upload is the one body this app sends that is not JSON. Handing the FormData to fetch
  // untouched is the whole difference: everything else here — the token, the CSRF header, the
  // 401 refresh and replay in `request`, the error envelope — applies to it unchanged.
  const isForm = body instanceof FormData;
  try {
    response = await fetch(BASE + path, {
      method,
      headers: buildHeaders(body !== undefined, method, isForm),
      body: body === undefined ? undefined : isForm ? body : JSON.stringify(body),
      // So the refresh cookie is sent once the backend sets one. `same-origin` rather than
      // `include`, because the console is served from the same origin as the API: in dev via
      // the Vite proxy, in production behind one host. `include` would additionally allow it
      // cross-origin, which is a door there is no reason to open.
      credentials: 'same-origin',
      signal,
    });
  } catch (cause) {
    // An aborted request is the caller's own doing, so pass it through untouched and let
    // them ignore it. Turning it into an ApiError would show the operator a false failure.
    if (cause?.name === 'AbortError') throw cause;
    throw new ApiError({
      status: 0,
      code: null,
      message: 'Cannot reach the server. Is the backend running on port 8080?',
      path,
    });
  }
  return { ok: response.ok, status: response.status, parsed: await parseBody(response) };
}

// One refresh at a time, shared by every caller that is waiting on it.
//
// This is not an optimisation, it is the whole correctness of the thing. The server rotates
// the refresh token on every use and treats a replay of an already-used token as a stolen
// token, revoking the entire session. Two requests that both hit 401 must therefore wait on
// ONE refresh rather than each sending the same token, or the second one signs the operator
// out and loses their work.
let refreshInFlight = null;

/**
 * Trades the refresh token for a new pair. Answers true when there is a usable access token
 * afterwards, false when the session is genuinely over. Never throws: the caller's own error
 * is the one worth reporting.
 */
function refreshSession() {
  if (refreshInFlight) return refreshInFlight;

  // The token goes in the body while the backend still reads it from there. Once it reads the
  // httpOnly cookie instead, this whole argument goes away and the browser supplies the token
  // on its own: see docs/refresh-cookie-spec.md. Sending no body on a page load is what makes
  // the change safe to land in either order, because a boot restore has nothing to send.
  const presented = refreshToken;
  refreshInFlight = send('POST', '/auth/refresh', {
    body: presented === null ? undefined : { refreshToken: presented },
  })
    .then((result) => {
      // Refresh returns a TokenPair and no user. Refreshing proves nothing new about who the
      // caller is, so the signed-in operator in AuthContext is left exactly as it was.
      if (!result.ok || !result.parsed?.accessToken) return false;
      setTokens({
        accessToken: result.parsed.accessToken,
        refreshToken: result.parsed.refreshToken ?? null,
      });
      return true;
    })
    .catch(() => false)
    .finally(() => {
      refreshInFlight = null;
    });

  return refreshInFlight;
}

// A page load gets exactly one restore attempt, and this remembers it.
//
// StrictMode runs every effect twice in development. Without this the second run would present
// a refresh token the first run has already spent, which is precisely the replay the server
// treats as theft. Once per load is also simply correct: either the cookie was there or it
// was not, and asking again cannot change the answer.
let restoreAttempt = null;

/**
 * Rebuilds the session after a page load, from the refresh cookie the browser still holds.
 *
 * Answers true when there is a usable access token afterwards. Answers false when there is no
 * session to restore, which is the ordinary case for somebody who has never signed in, and is
 * not an error worth showing anybody.
 *
 * Until the backend sets the cookie this always answers false, because a fresh page has no
 * refresh token in memory to send instead. That is why it fails quietly.
 */
export function restoreSession() {
  if (restoreAttempt === null) restoreAttempt = refreshSession();
  return restoreAttempt;
}

/**
 * One request. Returns parsed JSON, or null for 204.
 * Throws ApiError for anything that is not 2xx, and for a network failure.
 *
 * A 401 is usually just the fifteen-minute access token running out mid-session, so this
 * refreshes once and sends the request again. If the refresh also fails the session really is
 * over: the tokens are dropped, the auth failure handler runs, and the error is still thrown
 * so the caller knows its request did not happen.
 */
async function request(method, path, { body, signal, allowRefresh = true } = {}) {
  let result = await send(method, path, { body, signal });
  if (result.ok) return result.parsed;

  let error = toApiError(result.status, result.parsed, path);

  // Gated on the ACCESS token, not the refresh token: it means "we thought we had a session,
  // so a 401 is worth one refresh attempt". Gating on the refresh token would stop working the
  // day it moves into an httpOnly cookie, because then this file cannot see it at all.
  if (error.isAuthFailure && allowRefresh && accessToken !== null) {
    if (await refreshSession()) {
      result = await send(method, path, { body, signal });
      if (result.ok) return result.parsed;
      error = toApiError(result.status, result.parsed, path);
    }
  }

  if (error.isAuthFailure) {
    clearTokens();
    if (onAuthFailure) onAuthFailure();
  }
  throw error;
}

export const api = {
  get: (path, opts) => request('GET', path, opts),
  post: (path, body, opts) => request('POST', path, { ...opts, body }),
  put: (path, body, opts) => request('PUT', path, { ...opts, body }),
  patch: (path, body, opts) => request('PATCH', path, { ...opts, body }),
  del: (path, opts) => request('DELETE', path, opts),
};

/**
 * Turns page state into the query string every list endpoint expects.
 * `page` is zero based, matching the contract.
 */
export function pageQuery({ page = 0, size = 20, ...rest } = {}) {
  const params = new URLSearchParams({ page: String(page), size: String(size) });
  for (const [key, value] of Object.entries(rest)) {
    if (value !== undefined && value !== null && value !== '') params.set(key, String(value));
  }
  return `?${params.toString()}`;
}

/**
 * Walks every page of a list endpoint at the given page size and returns every item, for a
 * caller that needs the whole set rather than one page of it - an institution's full
 * entitlement history, say, not just what fits in the first 100. `fetchPage(page)` must
 * resolve to the contract's page shape: an object with `items` and `total`.
 *
 * `until` stops the walk early once the items collected so far satisfy it, checked before each
 * fetch - the same short-circuit ShelfPickedBooks needs to stop looking once every picked id is
 * already found, rather than paging through an entire catalogue for nothing.
 */
export async function fetchAllPages(fetchPage, { pageSize = 100, until } = {}) {
  const all = [];
  let page = 0;
  let total = Infinity;
  while (page * pageSize < total && !(until && until(all))) {
    const data = await fetchPage(page);
    total = data.total;
    all.push(...data.items);
    page += 1;
  }
  return all;
}
